### ISSUE TITLE
Error: select which range?

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#100]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-Fxh5AgumnAg

Error: select which range?
    at setRangeInContenteditable (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2531:15)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2503:9
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.35
* Started: 2018-01-10T05:30
* Now:     2018-01-10T05:30
* Elapsed: 9.367 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway 
Thanks, unfortunately I forgot to attach a piece of info there so I do not know what has happened. Please tell me what the error is next time. There is some type somewhere. (0.64.36, which I just uploaded for this purpose.)

**Comment by lborgman** [comment]
Found the error, fixing it tomorrow.

**Comment by lborgman** [comment]
Fixed (0.64.37)
