### ISSUE TITLE
Error: (404) when trying to fetch YouTube timed text

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#104]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?ytId=JZb1OhD-qfg&ytTitle=A%20Bugs%20Life%201998%20Full%20Movie%20-%20YouTube&ytTimedText=https%3A%2F%2Fwww.youtube.com%2Fapi%2Ftimedtext%3Fsignature%3D9FD333CE6CD1889F76420B2797E1E04CEA04AEA3.840B1DA05B5D7FCB33E251D7022DC40383E98763%26sparams%3Dasr_langs%252Ccaps%252Cv%252Cexpire%26hl%3Den_US%26caps%3Dasr%26key%3Dyttt1%26expire%3D1515659329%26v%3DJZb1OhD-qfg%26asr_langs%3Dde%252Cru%252Cpt%252Cen%252Cko%252Cja%252Ces%252Cit%252Cnl%252Cfr%26kind%3Dasr%26lang%3Des%26fmt%3Dsrv3

Error: (404)
when trying to fetch YouTube timed text
    at XMLHttpRequest.req.onload (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1920:24)

Error source:
* unhandledrejection

Context:
* Version: 0.64.39
* Started: 2018-01-11T14:12
* Now:     2018-01-11T14:12
* Elapsed: 4.62 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by MikeRidgway** [comment]
Here's the URL. The video is a knockoff version of "A Bug's Life" with English audio. YouTube incorrectly determined it to be in Spanish and created Spanish automatic captions for the video.

**Comment by lborgman** [comment]
@MikeRidgway  Thanks. Not sure how to handle that. I do not know if I can catch it. Do you have some idea?

**Comment by lborgman** [comment]
The error you see is due to the timeout on YouTube. I made a better error message (I actually did that before, but forgot to remove a line.)
