### ISSUE TITLE
TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#106]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-CYX0qBBhFMI

TypeError: Cannot read property 'click' of undefined
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:232:22

Error source:
* error

Context:
* Version: 0.64.39
* Started: 2018-01-11T14:16
* Now:     2018-01-11T14:28
* Elapsed: 712.849 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by MikeRidgway** [comment]
I just got this again when pressing Ctrl+Insert on a word where in non-edit mode.

**Comment by lborgman** [comment]
Fixed.
