### ISSUE TITLE
Error: addPunctuation no elt id, aw || On Ctrl+Enter press

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#108]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-CYX0qBBhFMI

Error: addPunctuation no elt id, aw
    at addPunctuation (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2001:25)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:471:13

Error source:
* error

Context:
* Version: 0.64.39
* Started: 2018-01-11T14:16
* Now:     2018-01-11T15:06
* Elapsed: 2997.733 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
I think I fixed this earlier today so I am closing this.
