### ISSUE TITLE
Improve positioning of inline play button on Enter press

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#109]
When the user presses enter to be able to directly edit a word, don't move the play button relative to that word. Just leave it where it is in that instance.

**Comment by lborgman** [comment]
Why is that better?

**Comment by MikeRidgway** [comment]
I find it mentally jarring for the word I'm diving into to suddenly jump to the other side of the play button. I would expect it to stay exactly where it is when I go to edit it. It's like my brain then goes, "where'd it go? And then I look around and go, "Oh, there it is." :-)

**Comment by lborgman** [comment]
I see what you mean... But I am not sure what to do.

This will happen whenever you edit a word after a play button on the same row. There could be many words to change on a row, sometimes.

I have been planning for an option to not have any play buttons in the edit part, but instead have a play button at the bottom. Would that be a good alternative?

**Comment by MikeRidgway** [comment]
I think so.

**Comment by lborgman** [comment]
I am implementing this option, but it is not quite ready yet. On my way I decided to try to make the arrow removing less jarring by smoothly removing them. This is in 0.64.59. What do you think?

**Comment by lborgman** [comment]
I have added on option for this too.
