### ISSUE TITLE
Error: Failed to execute 'setEnd' on 'Range': The offset 6 is larger than the node's length (5).

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#111]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-CYX0qBBhFMI

Error: Failed to execute 'setEnd' on 'Range': The offset 6 is larger than the node's length (5).
    at setRangeInContenteditable (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2524:15)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2507:9
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.39
* Started: 2018-01-11T18:38
* Now:     2018-01-11T18:39
* Elapsed: 30.575 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by MikeRidgway** [comment]
I'm able to get this to happen when I use an em dash character (pasted in or inserted using a macro).
Posting the error, assuming it's the same as above.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-CYX0qBBhFMI

Error: Failed to execute 'setEnd' on 'Range': The offset 12 is larger than the node's length (10).
    at setRangeInContenteditable (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2524:15)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2507:9
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.39
* Started: 2018-01-11T18:38
* Now:     2018-01-11T20:54
* Elapsed: 8177.301 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
There seems to be something strange with the handling of em dash in contenteditable fields. I suspect it is a Chrome bug, but I do not give it a high priority to investigate it now. Please avoid em-dash for now. Is it possible to use something like -- instead for now? (That could easily be changed in some post-processing.)

**Comment by lborgman** [comment]
@MikeRidgway  How do you insert em dash? Do you type it on your keyboard, or?

**Comment by MikeRidgway** [comment]
I have a macro program where I have created a macro that simply types an
em-dash character.  Recently, doing the same thing had no problems at all.

**Comment by lborgman** [comment]
Thanks @MikeRidgway 
I have not tested pasting an em dash for some while now. I will test it and see what happens here. Maybe I can close this issue after that.

**Comment by lborgman** [comment]
This was a bit difficult. I think it is nearly fixed now. I have to get caret positions correct too.

**Comment by lborgman** [comment]
It should work now. @MikeRidgway , please tell me if you see any problem now, ver 0.70.225.

(One problem that remains is the button I have created too insert em-dash. Not sure how that should work.)
