### ISSUE TITLE
TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#112]
On switching between the two editor modes, specifically from transcript to caption.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-L2RiXFCI9o0

TypeError: Cannot read property 'classList' of null
    at https://easycaped-1.firebaseapp.com/js/transcribe.js:236:29

Error source:
* error

Context:
* Version: 0.64.42
* Started: 2018-01-16T19:02
* Now:     2018-01-16T19:06
* Elapsed: 246.465 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway  Thanks, I think this is fixed in newer versions.
