### ISSUE TITLE
Possible repeat: TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#118]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=shared&key=YT-TFFxrpFyXaM

TypeError: Cannot read property 'click' of undefined
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:241:22

Error source:
* error

Context:
* Version: 0.64.46
* Started: 2018-01-19T23:44
* Now:     2018-01-19T23:48
* Elapsed: 264.577 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(shared)
* Captions
* Logged in

**Comment by lborgman** [comment]
Probably a duplicate. I think it is fixed now.
