### ISSUE TITLE
Edit focus being ignored in favor of non-edit focus when modifying words

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#119]
To dupe: Set edit focus on a word. Let the border focus advance to another word. Click any button. The wrong word will be modified.

**Comment by lborgman** [comment]
@MikeRidgway Thanks, yes, I seem to have mixed it up a bit there.

**Comment by lborgman** [comment]
I think it is fixed in 0.64.54, but there are many cases so I am not sure yet.
