### ISSUE TITLE
Esc sometimes doesn't end edit focus for words

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#120]
To duplicate. Press Enter to go into a word. Then press Esc. The video will start playing but edit focus will be maintained.

**Comment by lborgman** [comment]
@MikeRidgway  Thanks. I do not understand what is going on there, but I think there are some problems in this area right now because of the rewriting I have done with the key bindings.

Maybe it has been a problem with the YouTube player? I have turned off key bindings for the player now.

**Comment by lborgman** [comment]
It looks a bit harder than thought. I just observed that when i bind ctrl+d that binding sometimes works after that and other times not. 

I suspect that the iframe has something to do with it, but I am not sure. Maybe it is time to file a bug report for Chrome.

**Comment by lborgman** [comment]
I think I have fixed it. (The YouTube video player iframe could get DOM focus.)
