### ISSUE TITLE
TypeError: Cannot read property 'click' of undefined     at .js:241:22

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#121]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-mOrYqt5OA-M

TypeError: Cannot read property 'click' of undefined
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:241:22

Error source:
* error

Context:
* Version: 0.64.48
* Started: 2018-01-28T02:09
* Now:     2018-01-28T02:18
* Elapsed: 565.523 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Thanks @MikeRidgway 
Probably fixed in 0.64.53
Closing, but please reopen if you see it again.
