### ISSUE TITLE
ReferenceError: addTheSquireEventListeners is not defined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#122]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-mOrYqt5OA-M

ReferenceError: addTheSquireEventListeners is not defined
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:4347:17
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.55
* Started: 2018-01-29T12:00
* Now:     2018-01-29T12:04
* Elapsed: 235.168 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by MikeRidgway** [comment]
Occurred when I clicked on the Transcribe button.

**Comment by lborgman** [comment]
Thanks @MikeRidgway, this was probably a loading problem. I think it is fixed in 0.64.56 so I am closing this. Please tell me if it happens again.
