### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#123]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-mOrYqt5OA-M

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:4342:45
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.55
* Started: 2018-01-29T12:00
* Now:     2018-01-29T12:06
* Elapsed: 356.026 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Thanks, should not occur in 0.64.56 any more.
