### ISSUE TITLE
Punctuation insertion in transcription editor, 

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#124]
I'd suggest having punctuation keys work identically whether the caret is at the end of word N or at the beginning of word N+1.

so if the pipe character here represents the caret, then when the caret is in that location, the shortcuts will properly break those words into sentences. 

a bunch of words followed by a bunch of words **|**a bunch of words followed by a bunch of words**|** a bunch of words

**Comment by lborgman** [comment]
I would like it to work similar when editing captions and transcripts.

When editing captions in EasyCapEd your main position is always at a word. That is the unit of interest there, so to say.

So you can choose to put the punctuation after the current word or before it. There are no other choices that works all the time in the captions.

To me it feels much more intuitiv to put end a sentence after the current word than before it. It is similar to the flow of the text.

I suggest it should work the same way when editing a transcript

**Comment by MikeRidgway** [comment]
If you get the transcript editor working, that's the one I would have my
workers use primarily.

**Comment by lborgman** [comment]
I have removed the transcript editor for now. I am waiting for the new JavaScript DOM/API that allows more control over editing. I have added a test for this (which you can find in the help popup). So far my tests shows that it is not ready for use yet. Or, should I say "it is a mess, currently".

**Comment by lborgman** [comment]
You can't edit transcripts in EasyCapEd now. It, rather, you can, but the editing is the same as for caption. 

However you do not need a video any more. You can use a sound file.
