### ISSUE TITLE
TypeError: Cannot read property 'startW' of undefined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#126]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-qpmxUyBLrno

TypeError: Cannot read property 'startW' of undefined
    at setupAndStartToPlayWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2417:22)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2444:44

Error source:
* error

Context:
* Version: 0.64.57
* Started: 2018-01-30T06:06
* Now:     2018-01-30T06:07
* Elapsed: 40.586 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway  Thanks, fixed (0.64.61).
