### ISSUE TITLE
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#127]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-qpmxUyBLrno

TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at HTMLInputElement.<anonymous> (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1507:19)

Error source:
* error

Context:
* Version: 0.64.57
* Started: 2018-01-30T06:06
* Now:     2018-01-30T06:08
* Elapsed: 97.925 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway  Thanks. I guess this was from the context menu on the play arrow? I just removed that menu (0.64.61) so I am closing this.
