### ISSUE TITLE
Ctrl+Enter in word edit mode the very first word in the box puts in a period.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#130]
So "well would you look at that"
Becomes "Well. would you look at that.

**Comment by lborgman** [comment]
@MikeRidgway Thanks, I must check the punctuation functions.

I have been hesitating a bit (that is why you see this error), but I decided I will put punctuation after the current word. (And capitalize the next word.) If you think that is a bad idea I will add an option for making it your way instead.

**Comment by lborgman** [comment]
Hm, but this was just a simple bug. Will be fixed in the next version.
