### ISSUE TITLE
ReferenceError: justAnErrorTest is not defined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#133]
### Actual Behavior (if any)

Cane up immediately on opening the captions.

### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-plJhBTP2suY

ReferenceError: justAnErrorTest is not defined
    at https://easycaped-1.firebaseapp.com/js/error.js:197:24

Error source:
* error

Context:
* Version: 0.64.84
* Started: 2018-02-05T00:50
* Now:     2018-02-05T00:50
* Elapsed: 10.247 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Thanks @MikeRidgway 
So this new error reporting is working.
