### ISSUE TITLE
Error which came up at spontaneously when playback of the video reached the end.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#137]
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-l2ZOXKwEX_A

TypeError: Cannot read property 'toString' of undefined
    at transcriptId (https://easycaped-1.firebaseapp.com/js/transcribe.js:161:30)
    at transcribeIdx2WordId (https://easycaped-1.firebaseapp.com/js/transcribe.js:233:12)
    at transcribeFollowVideoToNext (https://easycaped-1.firebaseapp.com/js/transcribe.js:186:18)
    at https://easycaped-1.firebaseapp.com/js/transcribe.js:181:9

Error source:
* error

Context:
* Version: 0.65.30
* Started: 2018-02-24T06:02
* Now:     2018-02-24T06:11
* Elapsed: 543.966 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Transcript
* Logged in

**Comment by lborgman** [comment]
Thanks, fixed (0.65.77).
