### ISSUE TITLE
** Please give the error a title! ***

### ISSUE THREAD

**Issue by CSWood** [lborgman/easy-cap-ed#142]
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-bookmarklet.html

ReferenceError: exportImportCaptions4menu is not defined
    at <anonymous>:1:17

Error source:
* error

Context:
* Version: 0.65.88
* Started: 2019-04-02T10:40
* Now:     2019-04-02T10:44
* Elapsed: 287.314 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by lborgman** [comment]
Thanks CSWood. Should be fixed now (0.65.110)

I did not notice your report because of a change at github. Sorry for the delay.
