### ISSUE TITLE
Update broke keyboard input

### ISSUE THREAD

**Issue by dtmpsc** [lborgman/easy-cap-ed#149]
### Expected Behavior
keyboard shortcuts for editing
### Actual Behavior
Can not use keyboard as input, shortcut keys do not work.
Mouse input works, can click interface buttons below text, can edit text when clicked, but cannot exit input mode without clicking elsewhere with mouse.
### Steps to Reproduce
no known workarounds.

**Comment by lborgman** [comment]
We are discussing it here on Facebook: https://www.facebook.com/groups/easycaped/permalink/418291385509789/

**Comment by lborgman** [comment]
Fixed in version 0.68.351;
