### ISSUE TITLE
Attempted to load captions into editor

### ISSUE THREAD

**Issue by dtmpsc** [lborgman/easy-cap-ed#152]
### Expected Behavior (if any)
After clicking "fetch and edit" it should have displayed the editor
### Actual Behavior (if any)
error log
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?ytId=veo9m5-vTHA&ytTitle=(4)%20Rob%20Thomas%27%20Tank%20Collection%20-%20YouTube&ytTimedText=https%3A%2F%2Fwww.youtube.com%2Fapi%2Ftimedtext%3Fv%3Dveo9m5-vTHA%26asr_langs%3Dde%252Cen%252Ces%252Cfr%252Cit%252Cja%252Cko%252Cnl%252Cpt%252Cru%26caps%3Dasr%26hl%3Den%26ip%3D0.0.0.0%26ipbits%3D0%26expire%3D1581454512%26sparams%3Dip%252Cipbits%252Cexpire%252Cv%252Casr_langs%252Ccaps%26signature%3D1DACA867AAC3210F7F65E952C58510356BD99C9E.67BBBA1BC580E889DD623AF9A8FAD2597F5C8323%26key%3Dyt8%26kind%3Dasr%26lang%3Den%26fmt%3Djson3%26xorb%3D2%26xobt%3D3%26xovt%3D3

ReferenceError: div is not defined
    at mkCaptionsDivFromContents (https://easycaped-1.firebaseapp.com/js/msj/import-captions.mjs:16:36)
    at https://easycaped-1.firebaseapp.com/js/msj/import-captions.mjs:78:26

Error source:
* unhandledrejection

Context:
* Version: > 0.68.106
* Started: 2020-02-11T13:57
* Now:     2020-02-11T13:57
* Elapsed: 9.462 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
* Online: true
* Symbol(local)
* Captions
* Logged in

**Comment by dtmpsc** [comment]
screencast of error

https://screencast-o-matic.com/watch/cYnX23wtVR

**Comment by lborgman** [comment]
@dtmpsc 
Thanks for three bug report. This should be fixed now in version  0.68.668
