### ISSUE TITLE
Capitalize doesn't seem to work.

### ISSUE THREAD

**Issue by dtmpsc** [lborgman/easy-cap-ed#153]
### Expected Behavior (if any)
Pressing C or U or . does not capitalize a word.
### Actual Behavior (if any)
nothing, or error
### Steps to Reproduce (if any)
Pressing C or U or . does not capitalize a word
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-2OCbbUJhsog

ReferenceError: tnw is not defined
    at capitalizeElt (https://easycaped-1.firebaseapp.com/js/caped-editor.js:479:31)
    at checkCapitalize (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1938:21)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:1949:25

Error source:
* unhandledrejection

Context:
* Version: 0.68.668
* Started: 2020-02-13T18:39
* Now:     2020-02-13T18:41
* Elapsed: 133.712 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
* Online: true
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Thanks @dtmpsc, I think this is fixed now (0.70.219)
