### ISSUE TITLE
Doesn’t seem to work on iOS at present (even when signed in)

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#36]
This is the video URL I was attempting to edit on my iPhone in mobile Chrome browser...

https://youtu.be/sSxhJPBuKZ0

**Comment by lborgman** [comment]
Fixed for the moment. 

Google Chrome on iOS lacks window.IntersectionObserver at the moment. It will make EasyCapEd slower, but I hope that Chrome will get this capability on iOS too rather soon so I just let it be for now. Should it persist very long I might have to rethink.

If you still see this after a couple of months then please reopen this bug!
