### ISSUE TITLE
Issues when non-edit focus attaches to one word and we hve edit focus in a different word.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#37]
For example, pressing delete or backspace while another word has a dotted border results in the message "Nothing to reset at that word."

**Comment by lborgman** [comment]
Thanks. I am trying to get those focus together to only one node all the time. It is to difficult to have them on different nodes, both for the programmer and the user. (I simply started down the wrong road there and I am trying to find my way back.)

**Comment by lborgman** [comment]
Fixed.
