### ISSUE TITLE
Ctrl+Space not behaving like Shift+Space

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#40]
Shift+Space seems to behave as expected. It starts and stops playback. Ctrl+Space moves the focus to a different word typically on a different row.

**Comment by lborgman** [comment]
Oh. No, unfortunately not. 

Shift+Space should not be doing anything at the moment. I implemented that bad. Great that you tested it!

Can you explain more about what you find about Ctrl+Space? It should start playing the current word.

**Comment by lborgman** [comment]
Ctrl+space is now bound to "play current word" so I am closing this.
