### ISSUE TITLE
Obscure enter key bug.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#43]
If I press Enter several times very quickly, eventually it will get stuck in edit mode but there will be no visible cursor. Pressing tab moves the word highlighter forward through the transcript but the word in edit mode will say in apparent edit mode nonetheless.

0/65

**Comment by lborgman** [comment]
Thanks Mike. It is kind of things I do not want to know... :-(

There are some complicated issues with event order there. I am very glad for the report.

**Comment by lborgman** [comment]
Fixed (0.64.63).
