### ISSUE TITLE
Tab from the last word

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#46]
Tab from the last word moves focus to browser elements getting in two presses to the address bar.

**Comment by lborgman** [comment]
Thanks Mike. I can reproduce it by first entering editing at that word. 

I think this is an issue with the DOM element focus. (This is a problem in several other ways too.)

**Comment by lborgman** [comment]
Found a way to fix it (0.64.63). You can still reproduce it if you type very quickly though.
