### ISSUE TITLE
Shift+Tab problem when no key up on Shift.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#47]
Pressing Tab while holding down the Shift key continuously eventually results in the shift key state being ignored, and so a word right is effectuated instead of word left.

**Comment by lborgman** [comment]
Thanks Mike. I can't reproduce it here, though. Does it happen often?

BTW this could be an issue with the web browser/OS. Not sure if anything could be done.

**Comment by MikeRidgway** [comment]
I can produce the problem effortlessly in the Chrome browser.

**Comment by lborgman** [comment]
I wonder why I can't reproduce it. How long do you hold down Shift+Tab? How long is the video?

**Comment by lborgman** [comment]
Probably fixed now. The problem was that I did reset all the modifiers on keyup instead of just the modifier in the argument to keyup.
