### ISSUE TITLE
Error. Don't recall what I was doing.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#48]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-wGSB8P1wl1g

TypeError: Cannot read property 'substr' of undefined
    at capitalizeWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1576:19)
    at HTMLDivElement.<anonymous> (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1423:17)

Context:
* Error source: error
* 2018-01-03T23:28
* Version: 0.64
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
Thanks Mike. I think you removed punctuation by doing a "Reset word". The following code was probably run:

```javascript
            var onw = nextW.dataset.ow;
            if (capitalizeWord(onw) == tnw) {
```

Hm, those error reports helps me a lot.

**Comment by lborgman** [comment]
This part of the code has changed quite a bit and I think this bug is fixed. Not sure, but I am closing the report since the information here is not useful any more.
