### ISSUE TITLE
Obscure sequence gets error.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#49]
How I got this to occurr:

Went to the bottom, Then pressed and held Shft+Tab. As focus was moving backward in the document, I clicked in the text pane and the error message was displayed.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-wGSB8P1wl1g

Error: can't find word span
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2390:23

Error source:
* error

Context:
* Version: 0.64.01
* Started: 2018-01-04T10:44
* Now:     2018-01-04T10:46
* Elapsed: 103.238 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks. I am closing this now since I do not believe this particular can occur now.
