### ISSUE TITLE
Or how about a Chrome extension? Lots of free advertising.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#52]

**Comment by lborgman** [comment]
Thanks, I think advertising is available for the web version too. I will try to look into it when things are getting more finished.

**Comment by lborgman** [comment]
Did I misunderstand you? Do you mean advertising for the editor out in the editor?

The Google services used will not be free so there have to be some income.

**Comment by lborgman** [comment]
Now there is an extension for Chrome. And for Firefox. (But they are not on the stores yet. You have to have the link. So there is no advertising income.)
