### ISSUE TITLE
Error: Could be a repeat

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#53]
Repeated Tab presses were the last thing I did before getting this error

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=user&key=YT-wGSB8P1wl1g

Error: Failed to execute 'setStart' on 'Range': The offset 7 is larger than the node's length (4).
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2144:23

Error source:
* error

Context:
* Version: 0.64.01
* Started: 2018-01-04T14:48
* Now:     2018-01-04T14:48
* Elapsed: 21.934 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(user)
* Logged in

**Comment by lborgman** [comment]
Thanks, there are some difficult things around this. I am not sure exactly of the event sequence that the browser gives in cases like this. I have to make this an FMS too so I at least know what I am trying to do.

**Comment by lborgman** [comment]
@MikeRidgway 
I think this is fixed (0.64.20). Please reopen if you see it again.
