### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#54]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=user&key=YT-wGSB8P1wl1g

Error: Nothing to reset at that word 2
    at HTMLDivElement.<anonymous> (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1409:19)

Error source:
* error

Context:
* Version: 0.64.01
* Started: 2018-01-04T14:50
* Now:     2018-01-04T14:53
* Elapsed: 183.009 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(user)
* Logged in

**Comment by lborgman** [comment]
Thanks, on the slightly difficult list.

**Comment by lborgman** [comment]
Fixed (0.64.97)
