### ISSUE TITLE
Can we get a comma button? And maybe an em dash button too?

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#55]
Perhaps there could be a button that opens up a series of buttons for less frequently used but useful punctuation marks given that you don't have a lot of space for putting them in on mobile.

**Comment by MikeRidgway** [comment]
Perhaps there could be a button that opens up a series of buttons for less frequently used but useful punctuation marks given that you don't have a lot of space for putting them in on mobile.

**Comment by lborgman** [comment]
Ah, yes, thanks for the reminder, @MikeRidgway.

The comma is easy, but em dash seems difficult because at least Google Chrome does some unexpected things when I try to add it.

Could you describe more how em dash would be used? Then we could find a workaround.

**Comment by lborgman** [comment]
@MikeRidgway I just tested pasting an em dash. It seems to work now in Chrome. 

So I can add an em dash button and an em dash key binding now. But what would it insert? Just em dash or em dash surrounded by space?

**Comment by MikeRidgway** [comment]
Sounds like an item for options. :-)

**Comment by lborgman** [comment]
Implemented. Suggestion for enhancement are of course welcome, but closing this.
