### ISSUE TITLE
Set focus on first word on Ctrl+Home...

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#58]
... and on last word on Ctrl+End. Currently, focus stays on the focused word before those hotkeys are pressed, resulting in unexpected results when one then presses and arrow key or tab or starts video playback.

**Comment by lborgman** [comment]
I am not sure. It is the same problem with all user scrolling.

**Comment by lborgman** [comment]
@MikeRidgway Can you give me an argument for why it would be better to change focus in this particular case of scrolling? Why should it be handled different than pageup/pagedown? (I think it would be very confusing if pageup/pagedown changed the focused word.)

**Comment by lborgman** [comment]
I decided to implement you suggestion. I realized that home/end is already treated this way so why not ctrl-dito? This is now in next version. (Not uploaded yet, since I have been waiting for OK from you, @MikeRidgway )
