### ISSUE TITLE
Suggest moving case buttons to the second line, adding a no punctuation button to the first.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#60]
Maybe a simple circle/slash symbol, which in the context of the other buttons would say remove whatever is there.

**Comment by lborgman** [comment]
Thanks @MikeRidgway , I am not sure about this. Several buttons does perhaps not harm (if they do not take up more space on the screen)? Several buttons are often quicker and there is nothing to remember. It is not the same with key bindings, of course.

But, hm, I have made another decision for the red/green buttons.
