### ISSUE TITLE
F9 case converter: Suggested functionality

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#61]
Suggest the following functionality for F9 and Alt Page up.
No matter what the case of the text is, a first press always goes to Proper case.
Second press goes to ALL CAPS.
Third press goes to all lower.

This is advantageous over making this key an immediate toggle as Tab, F9 repeated in rapid succession would have the unfortunate effect of lower casing text that was already proper or upper case.  

(The same is suggested for the F2 key . First press would always turns the cell green, even if it's already green. Then a second press ungreens. or it could even be a threeway toggle between red green and nothing.)

**Comment by lborgman** [comment]
Proper case, is that the same as "capitalize"?

I think I disagree on the "green" because that would be frustrating for new users.

**Comment by lborgman** [comment]
Closing to avoid confusion. I think I have implemented the functionality for f9 that you have suggested later. (And I am thinking about the f2 part.)
