### ISSUE TITLE
Alt+Page Down and Alt+Page Up suggested functionality.

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#62]
Alt+Page Up.
First press always leaves the word with proper case. Second press produces All Caps.

Alt+Page Down always drops case one level.
If all caps, makes it proper case.
If proper case, makes word all lower case.
If word all lower case, has no effect.

**Comment by lborgman** [comment]
Ok, thanks, I got it, @MikeRidgway .

**Comment by lborgman** [comment]
Fixed (0.64.23)
But let third Alt+PageUp go to proper case again (because that was more simple).
