### ISSUE TITLE
Maintain edit focus state on word by word navigation regardless of shortcut

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#63]
If in non-edit mode, stay in non edit mode when shortcuts such as Tab, Shift+Tab, Right, Left, Up, and Down are pressed.

If in edit mode, invoke edit mode as each new word comes into focus.

In particular, if Ctrl+Right/Left is pressed when in edit mode, put editing cursor to the left of the first character in the word.

**Comment by lborgman** [comment]
Yes, good to get it here as a bug report, @MikeRidgway !

**Comment by lborgman** [comment]
Fixed.
