### ISSUE TITLE
More on Tab and Ctrl+Arrow keys

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#65]
Word+Right with Tab should position the cursor at the end of the word as it does now.
Word right/left with Ctrl+Right/Left should move edit focus to the next/previous word and position the cursor at the beginning of the word. Currently, edit focus is lost. As a result, there is no quick way to get to the beginning of the next word in the transcript.
  
I consider this a very high priority request as it will make a huge difference in the efficiency of work for human editors who are working on real keyboards.

**Comment by lborgman** [comment]
Yes, you are right @MikeRidgway , but this requires some work. I am thinking of how to do it first.

**Comment by lborgman** [comment]
Fixed (0.64.20)
