### ISSUE TITLE
Suggest a no video mode

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#66]
So that I can get a bigger view of the text that I'm working on. Right now even with a 21 inch monitor, I'm only getting about 3 1/2 rows of display.

**Comment by lborgman** [comment]
Thanks @MikeRidgway , yes a new CSS layout for desktops is badly needed. Putting the captions beside the video seems like a much better idea.

**Comment by lborgman** [comment]
Reduced the height of the video for the one column layout by 20%.
