### ISSUE TITLE
On page zoom out, make the video smaller ...

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#67]
... But increase substantially the number of rows being displayed and increase the row height and font size relative to other elements on the screen.

**Comment by lborgman** [comment]
Thanks @MikeRidgway . Not sure how to handle this.

**Comment by lborgman** [comment]
@MikeRidgway  I am not sure what is left to do here. What do you think?

**Comment by lborgman** [comment]
Do you mean I should reduce the video height when making the browser window wider and everything is still in one column?

**Comment by lborgman** [comment]
Reduced the height of the video in the one column mode by 20%.
