### ISSUE TITLE
Error while using on an Android device

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#68]
In URL: * https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=shared&key=YT-wGSB8P1wl1g Error: can't find word span at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2390:23 Error source: * error Context: * Version: 0.64.01 * Started: 2018-01-04T16:43 * Now: 2018-01-04T16:46 * Elapsed: 214.994 sec * Browser: Mozilla/5.0 (Linux; Android 6.0.1; Z978 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36 * Symbol(shared) * Logged in

**Comment by lborgman** [comment]
Thanks @MikeRidgway . Did this happen at the beginning of the line?

**Comment by lborgman** [comment]
Probably fixed.
