### ISSUE TITLE
Error when using “reset” button on an individual word

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#69]
Received this error after first capitalising a word, then making it all upper case and then making it all lower case and then hitting the reset button.
ie after using the c, u and d buttons and then reset on a word...

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT--uLul74XYjg

https://easycaped-1.firebaseapp.com/js/caped-editor.js:1409:28

Error source:
* error

Context:
* Version: 0.64.01
* Started: 2018-01-04T20:17
* Now:     2018-01-04T20:19
* Elapsed: 72.345 sec
* Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/15C153 Safari/604.1
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
Thanks @mlockrey . There are some bugs there and I am going to implement some kind of FMS for this area too.

**Comment by lborgman** [comment]
Fixed (0.64.97)
