### ISSUE TITLE
Can't even see one sentence of automatic captions using Chrome on Mac OS X

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#70]
![screen shot 2018-01-05 at 7 50 16 am](https://user-images.githubusercontent.com/17226874/34583799-2f72df38-f1ed-11e7-9fc1-74f90806c619.png)

Buttons are also not styled consistently...

**Comment by lborgman** [comment]
A clear case for a new layout on desktops size screens. ;-)

What size is that screen, @mlockrey ? (window.outerHeight, window.outerWidth)

**Comment by lborgman** [comment]
Fixed.
