### ISSUE TITLE
Latest error when using EasyCapEd on a Mac OS X Chrome Browser

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#71]
Note: Not fatal - was able to continue but it doesn't seem to accept button changes (such as adding periods)...

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-67zX5yPTRTk

TypeError: Cannot read property 'classList' of null
    at setSpokenSpan (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1788:24)
    at setTimeout (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2624:26)

Error source:
* error

Context:
* Version: 0.64.02
* Started: 2018-01-04T20:49
* Now:     2018-01-04T20:49
* Elapsed: 9.068 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3309.0 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
I did a workaround (> 0.64.04)

Can you still reproduce the problem, @mlockrey ?

**Comment by lborgman** [comment]
Closing. This is a browser bug and I made a work around.
