### ISSUE TITLE
Error: bad parameter 2 to page

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#77]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html

Error: bad parameter 2 to page
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:3234:75

Error source:
* error

Context:
* Version: 0.64.06
* Started: 2018-01-05T14:06
* Now:     2018-01-05T14:06
* Elapsed: 0.296 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by lborgman** [comment]
@MikeRidgway , what did you do to get this?

**Comment by lborgman** [comment]
Fixed (>0.64.09)
