### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#78]
On clicking the Download Transcript option in a page where no video was loaded because I clicked on the option to load the editor even though I wasn't on a YouTube page to start with.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html

TypeError: Cannot read property 'children' of undefined
    at downloadAsWebVTT (https://easycaped-1.firebaseapp.com/js/download.js:67:37)
    at <anonymous>:1:1

Error source:
* error

Context:
* Version: 0.64.06
* Started: 2018-01-05T14:06
* Now:     2018-01-05T14:08
* Elapsed: 112.656 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks, I need to clean up a bit there.

**Comment by lborgman** [comment]
Fixed.
