### ISSUE TITLE
Error: setting spoken on play arrow

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#81]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

Error: setting spoken on play arrow
    at setSpokenSpan (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1779:25)
    at forwardWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:639:5)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:401:35

Error source:
* error

Context:
* Version: 0.64.07
* Started: 2018-01-05T14:58
* Now:     2018-01-05T18:20
* Elapsed: 12135.733 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks, I think I fixed this. I forgot one corner case. Please reopen if it happens again. (> 0.64.09)
