### ISSUE TITLE
Current error when trying to use iOS chrome browser

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#84]
Screenshots to come

**Comment by mlockrey** [comment]
![img_1283](https://user-images.githubusercontent.com/17226874/34635457-b121efd2-f2e3-11e7-8d3f-c6d9e229054b.jpg)
![img_1284](https://user-images.githubusercontent.com/17226874/34635458-b2456e98-f2e3-11e7-8b79-590c718b65c3.jpg)

**Comment by lborgman** [comment]
@mlockrey Thanks, I guess that is when you have clicked the bookmarklet on YouTube? And this video:

https://www.youtube.com/watch?v=eCHO2fEEKME

I tested on my pc and see no problems there. The error message contains no line number. I guess that means that it does not come from the JavaScript engine. Could this be a browser bug? (Is that Safari on iOS?)

**Comment by lborgman** [comment]
Closing. Seems to be a browser bug. (And I make a work around for it, I believe.)
