### ISSUE TITLE
Error: setting spoken on play arrow

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#86]
Keystroke that triggered this was Shift+Tab.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

Error: setting spoken on play arrow
    at setSpokenSpan (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1787:25)
    at backwardWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:655:5)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:397:80

Error source:
* error

Context:
* Version: 0.64.09
* Started: 2018-01-06T14:05
* Now:     2018-01-06T14:08
* Elapsed: 158.868 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
Probably fixed in 0.64.10

Please tell me if you see this error again.
