### ISSUE TITLE
Error on opening in Firefox

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#87]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

removePlayArrows@https://easycaped-1.firebaseapp.com/js/caped-editor.js:1064:9
VideoPlayerYouTube/<@https://easycaped-1.firebaseapp.com/js/caped-editor.js:3020:73
g.H@https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPgx2pR/www-widgetapi.js:58:255
g.s@https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPgx2pR/www-widgetapi.js:109:60
g.I@https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPgx2pR/www-widgetapi.js:123:275
hb.prototype.g@https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPgx2pR/www-widgetapi.js:98:269
$a/h<@https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPgx2pR/www-widgetapi.js:87:26

Error source:
* error

Context:
* Version: 0.64.09
* Started: 2018-01-06T14:13
* Now:     2018-01-06T14:13
* Elapsed: 4.224 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks. I don't think there is any chance that it will work in Firefox at the moment. I have blocked all other browsers than Google Chrome. (You may use other browsers, but you will be warned.)
