### ISSUE TITLE
Shift+Space was the last thing I did before getting this error

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#88]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

TypeError: Cannot read property 'dataset' of null
    at findPNearSpan (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2277:44)
    at removePlayArrowsInRange (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1984:23)
    at setupAndStartToPlayWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2013:5)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2033:44

Error source:
* error

Context:
* Version: 0.64.09
* Started: 2018-01-06T15:58
* Now:     2018-01-06T15:59
* Elapsed: 89.948 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway  Thanks, very, very helpful. I do not think I can find all this issues myself. (Without going through the code very carefully. I might do that later, though. But without these kind of reports I would perhaps not be aware of what to look for.)

I think I have fixed this one now (> 0.64.09).
