### ISSUE TITLE
No caret when tabbing to new word with editing focus enabled

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#89]
If I have editing focus in a word and I press tab to go to the next word, the word will appear to have focus but even though the text of the word isn't selected, (blue background), there will be no editing cursor visible.

**Comment by lborgman** [comment]
I think this is a bug in Chrome. I will try to workaround it.

**Comment by lborgman** [comment]
@MikeRidgway BTW, I think you mean "caret", not "cursor".

**Comment by MikeRidgway** [comment]
I view the two words as synonyms but I'll say caret if that's what you
prefer. :-)

**Comment by lborgman** [comment]
Ah, yes. It has costed me a lot of trouble when searching info. 😐

**Comment by lborgman** [comment]
Fixed.

**Comment by lborgman** [comment]
Eh, no. I thought it was the problem with invisible caret at the end, but this is something else. I have to look at it again.

**Comment by lborgman** [comment]
@MikeRidgway 
Fixed. But there are some irritating bugs around this area. I will look into them. I think I have got enough info for that now, just need time.
