### ISSUE TITLE
Correct handling of Ctrl+Arrow when editing a word

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#91]
Ctrl+Arrow when editing a word box should do the following.
When the caret is anywhere but at the end of the string, Ctrl+Left should move the caret to the end of the box.

When the caret is anywhere but at the beginning of the string, Ctrl+Right should move the caret to the beginning of the box.

What is happening now is that the caret isn't moving but non-edit focus gets moved along in the transcript one word at a time.

**Comment by lborgman** [comment]
Fixed (0.64.20), but I might consider doing the same for Ctrl-Up/Down too.

**Comment by lborgman** [comment]
Done.
