### ISSUE TITLE
Ehancement request: Ctrl+Right/left

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#92]
When a user presses Ctrl+Right/Left, do the following.
If not in word-edit mode, move to the next or previous word keeping it in non-edit mode.
If in word-edit mode, 
If caret is at the far right of the edit box, and Ctrl+Right is pressed, move edit focus to the next word and set the caret at the beginning of the box.
Likewise, if caret is at the far left of the edit box, and Ctrl+Left is pressed, move edit focus to the previous word and set the caret at the beginning of the box. (Or caret, in this case, could be set at the end of the box.)

**Comment by lborgman** [comment]
@MikeRidgway Thanks. Nearly fixed, but I missed what you meant with the caret position.

**Comment by lborgman** [comment]
Fixed (0.64.20)
