### ISSUE TITLE
TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#93]
Clicking and navigating.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

TypeError: Cannot read property 'tagName' of null
    at getSpanFromPoint (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2458:55)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2473:13

Error source:
* error

Context:
* Version: 0.64.10
* Started: 2018-01-06T23:13
* Now:     2018-01-06T23:13
* Elapsed: 30.736 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks. I wonder if document.elementFromPoint returns null? That would be a browser bug. I have put in a test for that.

**Comment by lborgman** [comment]
No. My bad. I must learn to distinguish plus and minus. :-(

Fixed in 0.64.12
