### ISSUE TITLE
Error after Ctrl+R (page refresh)

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#95]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

TypeError: Cannot read property 'focus' of undefined
    at focusWodFromKeyboard (https://easycaped-1.firebaseapp.com/js/caped-editor.js:266:19)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:540:17

Error source:
* error

Context:
* Version: 0.64.18
* Started: 2018-01-07T11:09
* Now:     2018-01-07T11:09
* Elapsed: 3.309 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks, fixed (0.64.20)
