### ISSUE TITLE
Error: addPunctuation no elt id, aw

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#98]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-L2WYTjO5aWU

Error: addPunctuation no elt id, aw
    at addPunctuation (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1915:25)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:443:13

Error source:
* error

Context:
* Version: 0.64.34
* Started: 2018-01-09T14:24
* Now:     2018-01-09T14:28
* Elapsed: 247.668 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
I think it is gone.
